[General]
network = General
sim-time-limit=40s
#repeat = 5

############### Number of Resource Blocks ################
#**.carrierAggregation.componentCarrier[*].numerologyIndex = ${numerology=0}
#**.numBands = ${numBands=100} # this value should be kept equal to the number of RBs

**.carrierAggregation.componentCarrier[*].numerologyIndex = ${numerology=1}
**.numBands = ${numBands=50} # this value should be kept equal to the number of RBs

############### Transmission Power ##################
**.ueTxPower = 26dBm
**.eNodeBTxPower = 46dBm
**.targetBler = 0.01
**.blerShift = 5

**.gnb**.cellularNic.mac.**.statistic-recording = true #check it

############### IPv4 configurator config #################
*.configurator.config = xmldoc("./General.xml")
*.configurator.dumpAddresses = true
*.configurator.dumpRoutes = true
#*.carlaCommunicationManager.extraInitParams = parseJSON("{'config_name': 'unprotected_left_turn'}")

#*.router.interface[*].ipv4.netmask = "255.0.0.0"
#*.router.ppp1.ipAddress = "10.0.0.1"
#*.router.ppp[*].enableIpcp = false
#*.router.ppp[*].ipv4.netmask = "255.0.0.0"   # Set the correct subnet mask for the network
#**.router.ipv4.ipForwarding = true
#**.server.ipv4.netmask = "255.0.0.0"
#ipv4Netmask = 255.255.255.252 (inet::Ipv4Address)
# CARLA BASE MODULE CONFIGURATION
*.carlaCommunicationManager.moduleType = parseJSON("{'Vehicle': 'tod_network.nodes.CarlaCar', 'Pedestrian': 'tod_network.nodes.NRUwithMobility', 'EdgeCamera': 'tod_network.nodes.NRUwithMobility', 'SLDisturbing': 'tod_network.nodes.NRUwithMobility'}")
*.carlaCommunicationManager.moduleName = parseJSON("{'Vehicle': 'VectorVehicle', 'Pedestrian': 'VectorPedestrian', 'EdgeCamera': 'VectorEdgeCamera', 'SLDisturbing': 'VectorNRUeDISTURB'}")

*.VectorVehicle[*].macCellId = 0
*.VectorVehicle[*].masterId = 0
*.VectorVehicle[*].nrMacCellId = 1
*.VectorVehicle[*].nrMasterId = 1

*.VectorEdgeCamera[*].macCellId = 0
*.VectorEdgeCamera[*].masterId = 0
*.VectorEdgeCamera[*].nrMacCellId = 1
*.VectorEdgeCamera[*].nrMasterId = 1

*.VectorPedestrian[*].macCellId = 0
*.VectorPedestrian[*].masterId = 0
*.VectorPedestrian[*].nrMacCellId = 1
*.VectorPedestrian[*].nrMasterId = 1

*.VectorNRUeDISTURB[*].macCellId = 0
*.VectorNRUeDISTURB[*].masterId = 0
*.VectorNRUeDISTURB[*].nrMacCellId = 1
*.VectorNRUeDISTURB[*].nrMasterId = 1

#*.enableImplicitChunkSerialization = true

### Enable D2D for the eNodeB and the UEs involved in direct communications ###
**.amcMode = "D2D"

### Select CQI for D2D transmissions ###
# One-to-Many communications work with fixed CQI values only.
# Set the parameter **.usePreconfiguredTxParams and select the desired CQI using the parameter **.d2dCqi
**.enableD2DCqiReporting = true
**.usePreconfiguredTxParams = true
*.d2dCqi = ${cqi=7}


# D2D-capable flows are started in D2D mode
*.Vector*[*].cellularNic.d2dInitialMode = true

# MINIMAL NECESSARY CONFIGURATION FOR DYNAMIC GENERATED MODULES
*.Vector*[*].ipv4.configurator.typename = "HostAutoConfigurator"
*.Vector*[*].ipv4.configurator.interfaces = "cellular lo0"
*.Vector*[*].ipv4.configurator.mcastGroups = "224.0.0.3"


#NECESSARY TO CORRECT ROUTE PACKET (AGENT->VEHICLE) IN ROUTER
*.visualizer.displayRoutingTables = true

#GENERAL STANDARDS: server is remote TOD agent, VectorVehicle[0] is the hero vehicle controlled by TOD agent or onBoard agent (tod or onboard is directly setted in VectorVehicle[0].TODCarApp.zeroDelay)

#APP INSTALLATION
**.server.numApps = 1
**.server.app[0].typename = "TODAgentApp"
**.server.app[0].localPort = 3000
**.server.app[0].instructionMessageLength = 1000B
**.server.app[0].processingStatusTime = normal(15ms, 0.75ms)


#*.VectorVehicle[0].ipv4.configurator.forcedIP = "10.0.0.100"

*.VectorVehicle[0].numApps = 1
#TOD APP
*.VectorVehicle[0].app[0].typename = "TODCarApp"
*.VectorVehicle[0].app[0].destAddress = "server"
*.VectorVehicle[0].app[0].destPort = 3000
*.VectorVehicle[0].app[0].statusMessageLength = 33kB

*.VectorVehicle[*].app[*].encodingImageTime = normal(10ms, 0.5ms)
*.VectorVehicle[*].app[*].collectionDataTime = normal(15ms, 0.1ms)



#*.VectorNRUeDISTURB[*].numApps = 1
#COOP APP
#*.VectorNRUeDISTURB[*].app[0].typename = "CooperativePerceptionCarApp"
#*.VectorNRUeDISTURB[*].app[0].destAddressesCoop = "224.0.0.4"
#*.VectorNRUeDISTURB[*].app[0].destPort = 5000
#*.VectorNRUeDISTURB[*].app[0].statusUpdateIntervalCoop = 0.020s

#**.numUeD2DTx = ${SLDistrurbing=0, 5, 10}
#**.numTodBgUes = ${BgUe=0, 5, 10}


#**.numUeD2DTx = ${SLDistrurbing=0}
#**.numTodBgUes = ${BgUe=0}

##SL Distrurbing
# D2D-capable flows are started in D2D mode
**.ueD2DTx[*].cellularNic.d2dInitialMode = true

#**.numUeD2DTx = ${SLDistrurbing=0, 10}
# Place D2D endpoints far from the gNodeB (~50m) and close to each other (20m)
**.ueD2DTx[*].mobility.initFromDisplayString = false

**.ueD2DTx[*].macCellId = 0
**.ueD2DTx[*].masterId = 0
**.ueD2DTx[*].nrMacCellId = 1
**.ueD2DTx[*].nrMasterId = 1

**.ueD2DTx[0].numApps = 2
**.ueD2DTx[1..100].numApps = 1

**.ueD2DTx[*].app[0].typename = "UdpBasicApp"
**.ueD2DTx[*].app[0].destAddresses = "ueD2DTx[0]"
**.ueD2DTx[*].app[0].destPort = 1000
**.ueD2DTx[*].app[0].messageLength = 33kB
**.ueD2DTx[*].app[0].sendInterval = 0.020s
**.ueD2DTx[*].app[0].packetName = "UDPData-D2D"

**.ueD2DTx[0].app[1].typename = "UdpSink"
**.ueD2DTx[0].app[1].localPort = 1000


##UL/DL Disturbing
#**.numTodBgUes = ${BgUe=0, 10}

**.bgUeTod_1[*].mobility.initFromDisplayString = false

**.bgUeTod_1[*].macCellId = 0
**.bgUeTod_1[*].masterId = 0
**.bgUeTod_1[*].nrMacCellId = 1
**.bgUeTod_1[*].nrMasterId = 1

**.bgUeTod_1[0].numApps = 2
**.bgUeTod_1[1..100].numApps = 1

**.bgUeTod_1[*].app[0].typename = "UdpBasicApp"
**.bgUeTod_1[*].app[0].destAddresses = "bgUeTod_1[0]"
**.bgUeTod_1[*].app[0].destPort = 1000
**.bgUeTod_1[*].app[0].messageLength = 33kB
**.bgUeTod_1[*].app[0].sendInterval = 0.020s
**.bgUeTod_1[*].app[0].packetName = "UDPData-ULDL"

**.bgUeTod_1[0].app[1].typename = "UdpSink"
**.bgUeTod_1[0].app[1].localPort = 1000




#**.statusUpdateIntervalCoop = ${statusUpdateIntervalCoop=0.033s} #0.016s 60fps, 0.033 30fps
#**.statusUpdateInterval = ${statusUpdateInterval=0.033s} #0.016s 60fps, 0.033 30fps

**.statusMessageLengthCoop = ${statusMessageLengthCoop=1kB}
**.statusMessageLength = ${statusMessageLength=33kB}
