[PedestrianCross]
network = oneTOD
sim-time-limit=20s

############### Number of Resource Blocks ################
**.numBands = 50 # this value should be kept equal to the number of RBs

############### Transmission Power ##################
**.ueTxPower = 26
**.eNodeBTxPower = 46
**.targetBler = 0.01
**.blerShift = 5

############### IPv4 configurator config #################
*.configurator.config = xmldoc("./demo.xml")
*.configurator.dumpAddresses = true
*.configurator.dumpRoutes = true

# CARLA CONFIGURATION
*.carlaCommunicationManager.carlaConfiguration = ""
*.carlaCommunicationManager.networkActiveModuleType = ""
*.carlaCommunicationManager.extraInitParams = parseJSON("{'config_name': '_generated_red_light_violation-comb#agent_TTC_WITH_ROUTE'}")

*.carlaCommunicationManager.moduleType = parseJSON("{'Vehicle': 'tod_network.nodes.CarlaCar', 'Pedestrian': 'tod_network.nodes.CarlaCar', 'EdgeCamera': 'tod_network.nodes.EdgeCamera'}")
*.carlaCommunicationManager.moduleName = parseJSON("{'Vehicle': 'VectorVehicle', 'Pedestrian': 'VectorPedestrian', 'EdgeCamera': 'VectorEdgeCamera'}")

*.VectorVehicle[*].macCellId = 0
*.VectorVehicle[*].masterId = 0
*.VectorVehicle[*].nrMacCellId = 1
*.VectorVehicle[*].nrMasterId = 1

*.VectorEdgeCamera[*].macCellId = 0
*.VectorEdgeCamera[*].masterId = 0
*.VectorEdgeCamera[*].nrMacCellId = 1
*.VectorEdgeCamera[*].nrMasterId = 1

*.car2.macCellId = 0
*.car2.masterId = 0
*.car2.nrMacCellId = 1
*.car2.nrMasterId = 1

#*.enableImplicitChunkSerialization = true

# D2D-capable flows are started in D2D mode
*.VectorVehicle[*].cellularNic.d2dInitialMode = true

### Enable D2D for the eNodeB and the UEs involved in direct communications ###
**.amcMode = "D2D"

### Select CQI for D2D transmissions ###
# One-to-Many communications work with fixed CQI values only.
# Set the parameter **.usePreconfiguredTxParams and select the desired CQI using the parameter **.d2dCqi
**.enableD2DCqiReporting = true
**.usePreconfiguredTxParams = true
*.d2dCqi = ${cqi=7}

#**.ipv4.arp.typename = "GlobalArp"

#app installation
**.server.numApps = 1
#unused
#**.server.app[0].agentId = "car"
#used
**.server.app[0].typename = "TODAgentApp"
**.server.app[0].localPort = 3000
**.server.app[0].instructionMessageLength = 1000B
**.server.app[0].agentId = ""

#**.server.app[1].typename = "UdpSink"
#**.server.app[1].localPort = 5000

#**.server.app[1].typename = "CooperativePerceptionCarApp"
#**.server.app[1].destPort = 5000
#**.server.app[1].agentId = "Agent01"


*.VectorVehicle[*].ipv4.configurator.typename = "HostAutoConfigurator"
*.VectorVehicle[*].ipv4.configurator.interfaces = "cellular lo0"
*.VectorVehicle[*].ipv4.configurator.mcastGroups = "224.0.0.3"

*.VectorEdgeCamera[*].ipv4.configurator.typename = "HostAutoConfigurator"
*.VectorEdgeCamera[*].ipv4.configurator.interfaces = "cellular lo0"
*.VectorEdgeCamera[*].ipv4.configurator.mcastGroups = "224.0.0.3"

*.VectorVehicle[*].app[0].statusUpdateIntervalCoop = 0.020s

#unused
*.VectorVehicle[*].mobility.route = "simple_curve_world_1"
*.VectorVehicle[*].mobility.configuration_id = "simple_vehicle"
*.VectorVehicle[*].mobility.agent_configuration = "simple_agent"
#used
*.VectorVehicle[0].numApps = 2
#*.VectorVehicle[0].app[0].typename = "UdpBasicApp"
#*.VectorVehicle[0].app[0].destAddresses = "server"
#*.VectorVehicle[0].app[0].destPort = 6000
#*.VectorVehicle[0].app[0].messageLength = 1000B
#*.VectorVehicle[0].app[0].sendInterval = exponential(12ms)
#*.VectorVehicle[0].app[0].packetName = "UDPData-TOD"

*.VectorVehicle[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorVehicle[*].app[0].destAddressesCoop = "224.0.0.3"
*.VectorVehicle[*].app[0].destPort = 5000

#*.VectorVehicle[1].app[0].typename = "UdpSink"
#*.VectorVehicle[1].app[0].localPort = 5000

*.VectorVehicle[0].app[1].typename = "TODCarApp"
*.VectorVehicle[0].app[1].destAddress = "server"
*.VectorVehicle[0].app[1].destPort = 3000
*.VectorVehicle[0].app[1].agentConfiguration = "simple_agent"
*.VectorVehicle[0].app[1].statusMessageLength = 33kB
*.VectorVehicle[0].app[1].zeroDelay = ${zeroDelay=true, false}
#*.VectorVehicle[0].app[0].frameRate = ${frameRate=25, 60}

*.car2.numApps = 1
*.car2.app[0].typename = "UdpSink"
*.car2.app[0].localPort = 5000

*.VectorVehicle[1..5].numApps = ${coopApp=0,1}

#*.VectorVehicle[1].app[0].typename = "UdpSink"
#*.VectorVehicle[1].app[0].localPort = 3000

*.VectorPedestrian[*].mobility.typename = "TodCarlaInetMobility"
#*.VectorVehicle[2].app[0].typename = "CooperativePerceptionCarApp"
#*.VectorVehicle[2].app[0].destAddressesCoop = "224.0.0.3"
#*.VectorVehicle[2].app[0].destPort = 3000

*.VectorEdgeCamera[*].numApps = 1
*.VectorEdgeCamera[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorEdgeCamera[*].app[0].destAddressesCoop = "server"
*.VectorEdgeCamera[*].app[0].destPort = 5000
*.VectorEdgeCamera[*].cellularNic.d2dInitialMode = true
#unused
#*.VectorEdgeCamera[*].mobility.route = "simple_curve_world_1"
#*.VectorEdgeCamera[*].mobility.configuration_id = "simple_vehicle"
#*.VectorEdgeCamera[*].mobility.agent_configuration = "simple_agent"

# D2D-capable flows are started in D2D mode
*.car2.cellularNic.d2dInitialMode = true

#routing visualizer
*.visualizer.displayRoutingTables = true

############## STATUS AND INSTRUCTION PROCESSING ################
*.VectorVehicle[0].app[0].encodingImageTime = normal(10ms, 0.5ms)
*.VectorVehicle[0].app[0].collectionDataTime = normal(15ms, 0.1ms)

**.server.app[0].processingStatusTime = normal(15ms, 0.75ms)