[General]
network = oneTOD
sim-time-limit=200s

############### Number of Resource Blocks ################
**.numBands = 50 # this value should be kept equal to the number of RBs

############### Transmission Power ##################
**.ueTxPower = 26
**.eNodeBTxPower = 46
**.targetBler = 0.01
**.blerShift = 5

############### IPv4 configurator config #################
*.configurator.config = xmldoc("./demo.xml")
*.configurator.dumpAddresses = true
*.configurator.dumpRoutes = true

# CARLA CONFIGURATION
*.carlaCommunicationManager.carlaConfiguration = ""
*.carlaCommunicationManager.networkActiveModuleType = ""
*.carlaCommunicationManager.extraInitParams = parseJSON("{'config_name': 'c01'}")

*.carlaCommunicationManager.moduleType = parseJSON("{'Vehicle': 'tod_network.nodes.CarlaCar'}")
*.carlaCommunicationManager.moduleName = parseJSON("{'Vehicle': 'VectorVehicle'}")

*.VectorVehicle[*].macCellId = 0
*.VectorVehicle[*].masterId = 0
*.VectorVehicle[*].nrMacCellId = 1
*.VectorVehicle[*].nrMasterId = 1

*.car2.macCellId = 0
*.car2.masterId = 0
*.car2.nrMacCellId = 1
*.car2.nrMasterId = 1

*.VectorVehicle[*].ipv4.configurator.typename = "HostAutoConfigurator" 
*.VectorVehicle[*].ipv4.configurator.interfaces = "cellular lo0"
*.VectorVehicle[*].ipv4.configurator.mcastGroups = "224.0.0.3"
#*.VectorVehicle[*].ipv4.configurator.applyMcastG

# D2D-capable flows are started in D2D mode
*.VectorVehicle[*].cellularNic.d2dInitialMode = true

### Enable D2D for the eNodeB and the UEs involved in direct communications ###
**.amcMode = "D2D"

### Select CQI for D2D transmissions ###
# One-to-Many communications work with fixed CQI values only.
# Set the parameter **.usePreconfiguredTxParams and select the desired CQI using the parameter **.d2dCqi
**.enableD2DCqiReporting = true
**.usePreconfiguredTxParams = true
*.d2dCqi = ${cqi=7}

**.ipv4.arp.typename = "GlobalArp"

#app installation
**.server.numApps = 1
#unused
#**.server.app[0].agentId = "car"
#used
**.server.app[0].typename = "TODAgentApp"
**.server.app[0].localPort = 3000
**.server.app[0].instructionMessageLength = 1000B
**.server.app[0].agentId = ""
#*.server.app[0].typename = "UdpSink"
#*.server.app[0].localPort = 6000

#unused
*.VectorVehicle[0].mobility.route = "simple_curve_world_1"
*.VectorVehicle[0].mobility.configuration_id = "simple_vehicle"
*.VectorVehicle[0].mobility.agent_configuration = "simple_agent"
#used
*.VectorVehicle[*].numApps = 1
#*.VectorVehicle[0].app[0].typename = "UdpBasicApp"
#*.VectorVehicle[0].app[0].destAddresses = "server"
#*.VectorVehicle[0].app[0].destPort = 6000
#*.VectorVehicle[0].app[0].messageLength = 1000B
#*.VectorVehicle[0].app[0].sendInterval = exponential(12ms)
#*.VectorVehicle[0].app[0].packetName = "UDPData-TOD"
*.VectorVehicle[0].app[0].typename = "TODCarApp"
*.VectorVehicle[0].app[0].destAddress = "server"
*.VectorVehicle[0].app[0].destAddressesCoop = "224.0.0.3"
*.VectorVehicle[0].app[0].destPort = 3000
*.VectorVehicle[0].app[0].agentConfiguration = "simple_agent"
*.VectorVehicle[0].app[0].statusMessageLength = ${ulPkgSize= 33kB, 66kB} #12500B #200kB #12500B
*.VectorVehicle[0].app[0].frameRate = ${frameRate=25, 60}

*.car2.numApps = 1
*.car2.app[0].typename = "UdpSink"
*.car2.app[0].localPort = 3000

*.VectorVehicle[1].app[0].typename = "CooperativePerceptionCarApp"
*.VectorVehicle[1].app[0].destAddressesCoop = "224.0.0.3"
*.VectorVehicle[1].app[0].destPort = 3000

#*.car2.ipv4.configurator.typename = "HostAutoConfigurator" 
#*.car2.ipv4.configurator.interfaces = "cellular lo0"
#*.car2.ipv4.configurator.mcastGroups = "224.0.0.3"
#*.car2.ipv4.configurator.applyMcastG

# D2D-capable flows are started in D2D mode
*.car2.cellularNic.d2dInitialMode = true


############## STATUS AND INSTRUCTION PROCESSING ################
*.VectorVehicle[0].app[0].encodingImageTime = normal(10ms, 0.5ms)
*.VectorVehicle[0].app[0].collectionDataTime = normal(15ms, 0.1ms)

**.server.app[0].processingStatusTime = normal(15ms, 0.75ms)