include General.ini
[Config red_light_violation]
#gNodeb is used for reserve blocks in SIDELINK communications
*.carlaCommunicationManager.extraInitParams = parseJSON("{'config_name': 'red_light_violation'}")

**.ueD2DTx[*].mobility.initialX = -70m
**.ueD2DTx[*].mobility.initialY = 120m

**.bgUeTod_1[*].mobility.initialX = -50m
**.bgUeTod_1[*].mobility.initialY = 120m

[Config red_light_violation-noCooperativePerception]
extends = red_light_violation
*.VectorVehicle[0].app[0].zeroDelay = ${zeroDelay=true, false}


[Config red_light_violation-Vehicle2Vehicle]
extends = red_light_violation
#Vehicles send and receive informations using SIDELINK

*.VectorVehicle[0].numApps = 2
#COOP APP
*.VectorVehicle[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorVehicle[*].app[0].destAddressesCoop = "224.0.0.3"
*.VectorVehicle[*].app[0].destPort = 5000
#TOD APP
*.VectorVehicle[0].app[1].typename = "TODCarApp"
*.VectorVehicle[0].app[1].destAddress = "server"
*.VectorVehicle[0].app[1].destPort = 3000
*.VectorVehicle[0].app[1].zeroDelay = ${zeroDelay=true, false}

#1 => COOP APP INSTALLED, 0 => NO APP IS INSTALLED
*.VectorVehicle[1..100].numApps = 1

[Config red_light_violation-Infrastructure2Vehicle]
extends = red_light_violation
#edge device observe and send informations to Vehicles using 5G SIDELINK
#Vehicles do not send cooperative informations
*.VectorVehicle[0].numApps = 2
#COOP APP
*.VectorVehicle[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorVehicle[*].app[0].destAddressesCoop = "224.0.0.3"
*.VectorVehicle[*].app[0].destPort = 5000
*.VectorVehicle[*].app[0].onlyReceive = true
#TOD APP
*.VectorVehicle[0].app[1].typename = "TODCarApp"
*.VectorVehicle[0].app[1].destAddress = "server"
*.VectorVehicle[0].app[1].destPort = 3000
*.VectorVehicle[0].app[1].zeroDelay = ${zeroDelay=true, false}

*.VectorVehicle[1..100].numApps = 1

*.VectorEdgeCamera[*].numApps = 1
#COOP APP
*.VectorEdgeCamera[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorEdgeCamera[*].app[0].destAddressesCoop = "224.0.0.3"
*.VectorEdgeCamera[*].app[0].destPort = 5000



[Config red_light_violation-Infrastructure_to_Server]
extends = red_light_violation
#edge device observe and send informations directly to TOD agent

#app[0] is TOD CAR APP
*.VectorVehicle[0].app[0].zeroDelay = ${zeroDelay=true, false}

**.server.numApps = 2
#app[0] is "TODAgentApp"
**.server.app[1].typename = "CooperativePerceptionCarApp"
**.server.app[1].destPort = 5000
**.server.app[1].agentId = "Agent01" #specifying agentId the app only receive cooperative messages and send to AgentGenericMessage

*.VectorEdgeCamera[*].numApps = 1
*.VectorEdgeCamera[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorEdgeCamera[*].app[0].destAddressesCoop = "server"
*.VectorEdgeCamera[*].app[0].destPort = 5000











[Config red_light_violation-Device2Infrastructure_to_Server]
extends = red_light_violation
#edge device receive informations from Vehicles using 5G SIDELINK,and generate his view
#edge device send aggregated information directly to TOD agent
#multi edge device

**.server.numApps = 2
#app[0] is "TODAgentApp"
**.server.app[1].typename = "CooperativePerceptionCarApp"
**.server.app[1].destPort = 5000
**.server.app[1].agentId = "Agent01" #specifying agentId the app only receive cooperative messages and send to AgentGenericMessage


*.VectorEdgeCamera[*].numApps = 1
*.VectorEdgeCamera[*].app[0].typename = "CooperativePerceptionCarApp"
*.VectorEdgeCamera[*].app[0].destAddressesCoop = "server"
*.VectorEdgeCamera[*].app[0].destPort = 5000
#*.VectorEdgeCamera[*].app[0].onlyReceive = true